# Generated by Django 4.1.4 on 2022-12-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=200)),
                ('device_location', models.CharField(max_length=200)),
                ('device_lat', models.FloatField()),
                ('device_long', models.FloatField()),
                ('device_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('air', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
        ),
    ]
