# Generated by Django 4.1.4 on 2023-01-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_device_id_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('timestamp', 'reading_id')},
        ),
    ]
